services:
  app:
    container_name: z-mirror
    build:
      context: .
      dockerfile: Dockerfile
    command: bash start.sh
    restart: on-failure
    ports:
      - "76:76"
      - "8088:8088"
      - "8070:8070"
      - "8090:8090"
